task_manager/statuses/urls.py
from django.urls import path
from task_manager.statuses import views

app_name = 'statuses'

urlpatterns = [
    path('', views.ShowStatuses.as_view(), name='statuses'),
    path('create/', views.CreateStatus.as_view(), name='create_status'),
    path('<int:pk>/update/', views.UpdateStatus.as_view(), name='update_status'),
    path('<int:pk>/delete/', views.DeleteStatus.as_view(), name='delete_status'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager.views import IndexView, LoginUserView, LogoutUserView


urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('admin/', admin.site.urls),
]

task_manager/statuses/models.py
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=100, blank=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/statuses/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from task_manager.statuses.models import Status


class StatusForm(ModelForm):
    name = forms.CharField(label=_('Name'))

    class Meta:
        model = Status
        fields = ['name']

task_manager/statuses/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.db.models import ProtectedError

from task_manager.statuses.forms import StatusForm
from task_manager.statuses.models import Status
from task_manager.users.mixins import CustomLoginRequiredMixin


class ShowStatuses(CustomLoginRequiredMixin, ListView):
    """Show all statuses"""
    model = Status
    template_name = 'statuses/statuses_index.html'
    context_object_name = 'statuses'
    allow_empty = True


class CreateStatus(CustomLoginRequiredMixin,
                   SuccessMessageMixin,
                   CreateView):
    """Create new status"""
    model = Status
    template_name = 'form.html'
    form_class = StatusForm
    success_url = reverse_lazy('statuses:statuses')
    success_message = _('Status successfully created')
    extra_context = {
        'title': _('Create status'),
        'button_value': _('Create')
    }


class UpdateStatus(CustomLoginRequiredMixin,
                   SuccessMessageMixin,
                   UpdateView):
    """Update status"""
    model = Status
    template_name = 'form.html'
    form_class = StatusForm
    success_url = reverse_lazy('statuses:statuses')
    success_message = _('Status successfully updated')
    extra_context = {
        'title': _('Edit status'),
        'button_value': _('Update')
    }


class DeleteStatus(CustomLoginRequiredMixin,
                   SuccessMessageMixin,
                   DeleteView):
    """Delete status"""
    model = Status
    template_name = 'delete_confirmation_form.html'
    success_url = reverse_lazy('statuses:statuses')
    success_message = _('Status successfully deleted')
    extra_context = {
        'title': _('Delete status'),
    }

    deletion_denied_message = _('Cant delete status because it is in use')

    # Can't delete status because it's in use
    def form_valid(self, form):
        success_url = self.get_success_url()
        try:
            self.object.delete()
        except ProtectedError:
            messages.add_message(
                self.request,
                messages.ERROR,
                self.deletion_denied_message
            )
        else:
            messages.add_message(
                self.request,
                messages.SUCCESS,
                self.success_message
            )
        return HttpResponseRedirect(success_url)

task_manager/statuses/templates/statuses/delete_status.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<h1>{% translate 'Delete status' %}</h1>
<p>{% translate 'A you sure you want to delete' %} {{ object.username }} ?</p>
<form method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="{% translate 'Yes, delete' %}">
</form>
{% endblock %}

task_manager/statuses/templates/statuses/statuses_index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<h1 class="my-4">{% translate 'Statuses' %}</h1>
<a class="nav-link" href="{% url 'statuses:create_status' %}">{% translate 'Create status' %}</a>
<table class="table table-striped">
    <thead>
      <tr>
        <th>{% translate 'ID' %}</th>
        <th>{% translate 'Name' %}</th>
        <th>{% translate 'Date of creation' %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        {% for status in statuses %}
        <tr>
          <td>{{ status.pk }}</td>
          <td>{{ status }}</td>
          <td>{{ status.created_at }}</td>
          <td>
            <a href="{% url 'statuses:update_status' pk=status.pk %}">{% translate 'Edit' %}</a>
            <br>
            <a href="{% url 'statuses:delete_status' pk=status.pk %}">{% translate 'Delete' %}</a>
          </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
  {% endblock %}