task_manager/labels/urls.py
from django.urls import path
from task_manager.labels import views

app_name = 'labels'

urlpatterns = [
    path('', views.ShowLabels.as_view(), name='labels'),
    path('create/', views.CreateLabel.as_view(), name='create_label'),
    path('<int:pk>/update/', views.UpdateLabel.as_view(), name='update_label'),
    path('<int:pk>/delete/', views.DeleteLabel.as_view(), name='delete_label'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager.views import IndexView, LoginUserView, LogoutUserView


urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('admin/', admin.site.urls),
]

task_manager/labels/models.py
from django.db import models


class Label(models.Model):
    name = models.CharField(max_length=100, blank=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/labels/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from task_manager.labels.models import Label


class LabelForm(ModelForm):

    class Meta:
        model = Label
        fields = ['name']
        labels = {
            'name': _('Name')
        }

task_manager/labels/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.db.models import ProtectedError

from task_manager.labels.forms import LabelForm
from task_manager.labels.models import Label
from task_manager.users.mixins import CustomLoginRequiredMixin


class ShowLabels(CustomLoginRequiredMixin, ListView):
    """Show all labels"""
    model = Label
    template_name = 'labels/labels_list.html'
    context_object_name = 'labels'
    allow_empty = True


class CreateLabel(CustomLoginRequiredMixin,
                  SuccessMessageMixin,
                  CreateView):
    """Create new label"""
    model = Label
    template_name = 'form.html'
    form_class = LabelForm
    success_url = reverse_lazy('labels:labels')
    success_message = _('Label successfully created')
    extra_context = {
        'title': _('Create label'),
        'button_value': _('Create')
    }


class UpdateLabel(CustomLoginRequiredMixin,
                  SuccessMessageMixin,
                  UpdateView):
    """Update label"""
    model = Label
    template_name = 'form.html'
    form_class = LabelForm
    success_url = reverse_lazy('labels:labels')
    success_message = _('Label successfully updated')
    extra_context = {
        'title': _('Edit label'),
        'button_value': _('Update')
    }


class DeleteLabel(CustomLoginRequiredMixin,
                  DeleteView):
    """Delete label"""
    model = Label
    template_name = 'delete_confirmation_form.html'
    success_url = reverse_lazy('labels:labels')
    success_message = _('Label successfully deleted')
    extra_context = {
        'title': _('Delete label'),
    }
    deletion_denied_message = _('Cant delete label because it is in use')

    # Can't delete label because it's in use
    def form_valid(self, form):
        success_url = self.get_success_url()
        try:
            self.object.delete()
        except ProtectedError:
            messages.add_message(
                self.request,
                messages.ERROR,
                self.deletion_denied_message
            )
        else:
            messages.add_message(
                self.request,
                messages.SUCCESS,
                self.success_message
            )
        return HttpResponseRedirect(success_url)

task_manager/labels/templates/labels/delete_label.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<h1>{% translate 'Delete label' %}</h1>
<p>{% translate 'A you sure you want to delete' %} {{ object.username }} ?</p>
<form method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="{% translate 'Yes, delete' %}">
</form>
{% endblock %}

task_manager/labels/templates/labels/labels_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<h1 class="my-4">{% translate 'Labels' %}</h1>
<a class="nav-link" href="{% url 'labels:create_label' %}">{% translate 'Create label' %}</a>
<table class="table table-striped">
    <thead>
      <tr>
        <th>{% translate 'ID' %}</th>
        <th>{% translate 'Name' %}</th>
        <th>{% translate 'Date of creation' %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        {% for label in labels %}
        <tr>
          <td>{{ label.pk }}</td>
          <td>{{ label }}</td>
          <td>{{ label.created_at }}</td>
          <td>
            <a href="{% url 'labels:update_label' pk=label.pk %}">{% translate 'Edit' %}</a>
            <br>
            <a href="{% url 'labels:delete_label' pk=label.pk %}">{% translate 'Delete' %}</a>
          </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
  {% endblock %}