task_manager/tasks/urls.py
from django.urls import path
from task_manager.tasks import views


app_name = 'tasks'

urlpatterns = [
    path('', views.TasksList.as_view(), name='tasks'),
    path('create/', views.CreateTask.as_view(), name='create_task'),
    path('<int:pk>', views.ShowTask.as_view(), name='show_task'),
    path('<int:pk>/update/', views.UpdateTask.as_view(), name='update_task'),
    path('<int:pk>/delete/', views.DeleteTask.as_view(), name='delete_task'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager.views import IndexView, LoginUserView, LogoutUserView


urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('admin/', admin.site.urls),
]

task_manager/tasks/models.py
from django.db import models

from task_manager.statuses.models import Status
from task_manager.users.models import CustomUser
from task_manager.labels.models import Label


class Task(models.Model):
    name = models.CharField(max_length=100, blank=False, unique=True)
    description = models.TextField(max_length=1000, blank=True)
    status = models.ForeignKey(Status, on_delete=models.PROTECT, null=False)
    author = models.ForeignKey(
        CustomUser,
        on_delete=models.PROTECT,
        null=False,
        related_name='author'
    )
    executor = models.ForeignKey(
        CustomUser,
        on_delete=models.PROTECT,
        blank=True,
        null=True,
        related_name='executor'
    )
    labels = models.ManyToManyField(
        Label,
        through='TaskLabelRelationModel',
        through_fields=('task', 'label'),
        blank=True,
        default='')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TaskLabelRelationModel(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    label = models.ForeignKey(Label, on_delete=models.PROTECT)

task_manager/tasks/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from task_manager.tasks.models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'executor', 'labels']
        labels = {
            'name': _('Name'),
            'description': _('Description'),
            'status': _('Status'),
            'executor': _('Executor'),
            'labels': _('Labels')
        }

task_manager/tasks/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django_filters.views import FilterView

from task_manager.tasks.models import Task
from task_manager.tasks.forms import TaskForm
from task_manager.tasks.filters import TaskFilter
from task_manager.users.mixins import CustomLoginRequiredMixin, CustomUserPassesTestMixin
from task_manager.users.models import CustomUser


class TasksList(CustomLoginRequiredMixin, FilterView, ListView):
    """Show all tasks"""
    model = Task
    template_name = 'tasks/tasks_list.html'
    context_object_name = 'taskslist'
    allow_empty = True
    filterset_class = TaskFilter
    extra_context = {
        'button_value': _('Show')
    }


class ShowTask(CustomLoginRequiredMixin, DetailView):
    """Show tasks detail"""
    model = Task
    template_name = 'tasks/show_task.html'
    context_object_name = 'task'


class CreateTask(CustomLoginRequiredMixin,
                 SuccessMessageMixin,
                 CreateView):
    """Create new task"""
    model = Task
    template_name = 'form.html'
    form_class = TaskForm
    success_url = reverse_lazy('tasks:tasks')
    success_message = _('Task successfully created')
    extra_context = {
        'title': _('Create task'),
        'button_value': _('Create')
    }

    def form_valid(self, form):
        user_pk = self.request.user.pk
        form.instance.author = CustomUser.objects.get(pk=user_pk)
        return super().form_valid(form)


class UpdateTask(CustomLoginRequiredMixin,
                 SuccessMessageMixin,
                 UpdateView):
    """Update task"""
    model = Task
    template_name = 'form.html'
    form_class = TaskForm
    success_url = reverse_lazy('tasks:tasks')
    success_message = _('Task successfully updated')
    extra_context = {
        'title': _('Edit task'),
        'button_value': _('Update')
    }


class DeleteTask(CustomLoginRequiredMixin,
                 CustomUserPassesTestMixin,
                 SuccessMessageMixin,
                 DeleteView):
    """Delete task"""
    model = Task
    template_name = 'delete_confirmation_form.html'
    success_url = reverse_lazy('tasks:tasks')
    success_message = _('Task successfully deleted')
    extra_context = {
        'title': _('Delete task'),
    }
    my_perm_denied_url_string = 'tasks:tasks'
    permission_denied_message = _('Only author can delete task')

    # Check if user is author of task
    def test_func(self):
        task = self.get_object()
        return task.author.pk == self.request.user.pk

task_manager/tasks/templates/tasks/delete_task.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<h1>{% translate 'Delete task' %}</h1>
<p>{% translate 'A you sure you want to delete' %} {{ object.username }} ?</p>
<form method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="{% translate 'Yes, delete' %}">
</form>
{% endblock %}

task_manager/tasks/templates/tasks/show_task.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<h1 class="my-4">{% translate 'Task view' %}</h1>
    
<div class="card">
<div class="card-header bg-secondary text-white">
  <h2>{{ task }}</h2>
</div>
<div class="card-body bg-light">
  <p>{{ task.description }}</p>
  <hr>
  <div class="container">
    <div class="row p-1">
      <div class="col">{% translate 'Author' %}</div>
      <div class="col">{{ task.author }}</div>
    </div>
    <div class="row p-1">
      <div class="col">{% translate 'Executor' %}</div>
      <div class="col">{{ task.executor }}</div>
    </div>
    <div class="row p-1">
      <div class="col">{% translate 'Status' %}</div>
      <div class="col">{{ task.status }}</div>
    </div>
    <div class="row p-1">
      <div class="col">{% translate 'Date of creation' %}</div>
      <div class="col">{{ task.created_at }}</div>
    </div>
    <div class="row p-1">
      <div class="col">
        <h6>{% translate 'Labels' %}</h6>
        <ul>
          {% for label in task.labels.all %}
            <li>{{ label }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="row p-1">
      <div class="col">
        <a href="{% url 'tasks:update_task' pk=task.pk %}">{% translate 'Edit' %}</a>
        <br>
        <a href="{% url 'tasks:delete_task' pk=task.pk %}">{% translate 'Delete' %}</a>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

task_manager/tasks/templates/tasks/tasks_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<h1 class="my-4">{% translate 'Tasks' %}</h1>
<a class="nav-link" href="{% url 'tasks:create_task' %}">{% translate 'Create task' %}</a>

<div class="card mb-3">
  <div class="card-body bg-light">
    <form class="form-inline center" method="get">
      {% bootstrap_form filter.form %}
      {% bootstrap_button button_value button_type="submit" button_class="btn-primary" %}

    </form>
  </div>
</div>

<table class="table table-striped">
    <thead>
      <tr>
        <th>{% translate 'ID' %}</th>
        <th>{% translate 'Name' %}</a></th>
        <th>{% translate 'Status' %}</th>
        <th>{% translate 'Author' %}</th>
        <th>{% translate 'Executor' %}</th>
        <th>{% translate 'Date of creation' %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        {% for task in taskslist %}
        <tr>
          <td>{{ task.pk }}</td>
          <td><a href="{% url 'tasks:show_task' pk=task.pk %}">{{ task.name }}</a></td>
          <td>{{ task.status }}</td>
          <td>{{ task.author }}</td>
          <td>{% firstof task.executor " " %}</td>
          <td>{{ task.created_at }}</td>
          <td>
            <a href="{% url 'tasks:update_task' pk=task.pk %}">{% translate 'Edit' %}</a>
            <br>
            <a href="{% url 'tasks:delete_task' pk=task.pk %}">{% translate 'Delete' %}</a>
          </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
  {% endblock %}