task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager.views import IndexView, LoginUserView, LogoutUserView


urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('admin/', admin.site.urls),
]

task_manager/users/urls.py
from django.urls import path
from task_manager.users import views

app_name = 'users'

urlpatterns = [
    path('', views.UsersList.as_view(), name='users'),
    path('create/', views.RegisterUser.as_view(), name="register"),
    path('<int:pk>/update/', views.UpdateUser.as_view(), name="update_user"),
    path('<int:pk>/delete/', views.DeleteUser.as_view(), name="delete_user")
]

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    """User model"""

    def __str__(self):
        return self.get_full_name()

task_manager/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from task_manager.users.models import CustomUser


class RegistrationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    password1 = forms.CharField(label=_("Password"), widget=forms.PasswordInput)
    password2 = forms.CharField(
        label=_("Password confirmation"), widget=forms.PasswordInput
    )

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username', 'password1', 'password2']

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

task_manager/users/views.py
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from task_manager.users.forms import RegistrationForm, UserUpdateForm
from task_manager.users.models import CustomUser
from task_manager.users.mixins import CustomLoginRequiredMixin, CustomUserPassesTestMixin

from django.http import HttpResponseRedirect
from django.contrib import messages
from django.db.models import ProtectedError


class UsersList(ListView):
    """Show users on page users"""
    model = CustomUser
    template_name = 'users/userlist.html'
    context_object_name = 'user_list'

    def get_queryset(self):
        return CustomUser.objects.all()


class RegisterUser(SuccessMessageMixin, CreateView):
    """Create new user"""
    template_name = 'users/form.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('login')
    success_message = _('User successfully registered!')
    extra_context = {
        'title': _('Registration'),
        'button_value': _('Register')
    }


class UpdateUser(CustomLoginRequiredMixin,
                 CustomUserPassesTestMixin,
                 SuccessMessageMixin,
                 UpdateView):
    """
    Change user.
    User shoud be logged in and can update only themself.
    """
    login_url = '/login/'
    login_required_message = _('You are not authorized! Please, log in.')

    model = CustomUser
    template_name = 'users/form.html'
    form_class = UserUpdateForm
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('users:users')
    success_message = _('You profile been updated!')
    extra_context = {
        'title': _('User update'),
        'button_value': _('Update')
    }

    my_perm_denied_url_string = 'users:users'
    permission_denied_message = _("You have no permission to change other user")


class DeleteUser(CustomLoginRequiredMixin,
                 CustomUserPassesTestMixin,
                 DeleteView):
    """
    Delete user.
    User shoud be logged in and can delete only themself.
    """
    login_url = '/login/'
    login_required_message = _('You are not authorized! Please, log in.')

    model = CustomUser
    template_name = 'users/delete_user.html'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('users:users')
    success_message = _('User was deleted')

    my_perm_denied_url_string = 'users:users'
    permission_denied_message = _("You have no permission to change other user")

    deletion_denied_message = _('Cannot delete user because it is in use')

    # Impossible to delete user if user have linked task
    def form_valid(self, form):
        success_url = self.get_success_url()
        try:
            self.object.delete()
        except ProtectedError:
            messages.add_message(
                self.request,
                messages.ERROR,
                self.deletion_denied_message
            )
        else:
            messages.add_message(
                self.request,
                messages.SUCCESS,
                self.success_message
            )
        return HttpResponseRedirect(success_url)

task_manager/users/templates/users/delete_user.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<h1>{% translate 'Delete user' %}</h1>
<p>{% translate 'A you sure you want to delete' %} {{ object.username }} ?</p>
<form method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="{% translate 'Yes, delete' %}">
</form>
{% endblock %}

task_manager/users/templates/users/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<h1>{{ title }}</h1>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_value button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}

task_manager/users/templates/users/userlist.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<h1 class="my-4">{% translate 'Users' %}</h1>
<table class="table table-striped">
    <thead>
      <tr>
        <th>{% translate 'ID' %}</th>
        <th>{% translate 'Username' %}</th>
        <th>{% translate 'Full name' %}</th>
        <th>{% translate 'Date of creation' %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        {% for user in user_list %}
        <tr>
          <td>{{ user.pk }}</td>
          <td>{{ user.username }}</td>
          <td>{{ user.first_name }} {{ user.last_name }}</td>
          <td>{{ user.date_joined }}</td>
          <td>
            <a href="{% url 'users:update_user' pk=user.pk %}">{% translate 'Edit' %}</a>
            <br>
            <a href="{% url 'users:delete_user' pk=user.pk %}">{% translate 'Delete' %}</a>
          </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
  {% endblock %}